name: Go

on:
  push:
    tags:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1-buster
      env:
        TZ: "Asia/Chongqing"
        
    steps:
    - uses: actions/checkout@v2

    - uses: little-core-labs/get-git-tag@v3.0.2
      id: tagName
      with:
        tagRegex: "v(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
        tagRegexGroup: 1 # Optional. Default is 1.
       
    - name: Prepare Build
      env:
        GOARCH: amd64
        GOOS: linux
      run: |
        make clean
        make ready

    # # Temporarily closed due to network problems
    # - name: Test
    #   run: go test -v ./...
      
    - name: App version
      run: export APP_VERSION=v${{ steps.tagName.outputs.tag }}
      
    - run: apt update
    - run: apt install upx -y
    
    - name: Build Linux amd64
      env:
        GOARCH: amd64
        GOOS: linux
      run: |
        make build
        upx -9 ./dist/lopy_ddns_linux_amd64
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload a Release Asset for linux
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/lopy_ddns_linux_amd64
        asset_name: lopy_ddns_linux_amd64
        asset_content_type: application/x-executable
